apiVersion: v1
kind: Service
metadata:
  name: dev-metauniv-front-svc
  labels:
    app: dev-metauniv-front
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: dev-metauniv-front
---
apiVersion: v1
kind: Service
metadata:
  name: dev-metauniv-back-svc
  labels:
    app: dev-metauniv-back
spec:
  ports:
    - port: 3080
  selector:
    app: dev-metauniv-back
