apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-metauniv-front-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prod-metauniv-front
  replicas: 4
  template:
    metadata:
      labels:
        app: prod-metauniv-front
    spec:
      containers:
      - name: prod-metauniv-front
        image: forargo.azurecr.io/web-front-server:v3
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-metauniv-back-deployment
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: prod-metauniv-back
  replicas: 4
  template:
    metadata:
      labels:
        app: prod-metauniv-back
    spec:
      containers:
      - name: prod-metauniv-back
        image: forargo.azurecr.io/web-back-server:v3
        ports:
        - containerPort: 3080
